version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: employee_db
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
